name: Setup envtest
description: A GitHub Action for setting up controller-runtime envtest
author: Flux project
branding:
  color: blue
  icon: command
inputs:
  version:
    description: 'Kubernetes version'
    required: false
    default: "latest"
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.version }}
