name: Setup Helm CLI
description: A GitHub Action for installing the Helm CLI
author: Flux project
branding:
  color: blue
  icon: command
inputs:
  version:
    description: Strict SemVer of the Helm CLI to install. Defaults to the latest release.
    required: false
runs:
  using: composite
  steps:
    - name: Download the binary to the runner's cache dir
      shell: bash
      run: |
        VERSION=${{ inputs.version }}
        if [[ -z "$VERSION" ]] || [[ "$VERSION" = "latest" ]]; then
          VERSION=$(curl -fsSL -H "Authorization: token ${{github.token}}" https://api.github.com/repos/helm/helm/releases/latest | grep tag_name | cut -d '"' -f 4)
        fi
        if [[ -z "$VERSION" ]]; then
          echo "Unable to determine Helm version"
          exit 1
        fi
        if [[ ! $VERSION = v* ]]; then
          VERSION="v${VERSION}"
        fi

        OS=$(echo "${RUNNER_OS}" | tr '[:upper:]' '[:lower:]')
        ARCH=$(echo "${RUNNER_ARCH}" | tr '[:upper:]' '[:lower:]')
        
        HELM_EXEC_FILE="helm"
        if [[ "$OS" == "windows" ]]; then
            HELM_EXEC_FILE="${HELM_EXEC_FILE}.exe"
        fi

        HELM_TOOL_DIR="${RUNNER_TOOL_CACHE}/helm/${VERSION}/${OS}/${ARCH}"
        if [[ ! -x "${HELM_TOOL_DIR}/${HELM_EXEC_FILE}" ]]; then
          # Download the installer.
          HELM_INSTALLER_TMP="$(mktemp -t helm-installer-XXXXXX)"
          curl -fsSL -o "$HELM_INSTALLER_TMP" https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod +x "$HELM_INSTALLER_TMP"

          # Run the installer.
          echo "Running Helm installer"
          mkdir -p "$HELM_TOOL_DIR"
          if [[ "$OS" = "macos" ]]; then
            # Workaround for "helm not found. Is "<path>" on your $PATH?
            export PATH="$HELM_TOOL_DIR:$PATH"
          fi
          USE_SUDO=false HELM_INSTALL_DIR="$HELM_TOOL_DIR" VERIFY_CHECKSUM=true VERIFY_SIGNATURES=false "$HELM_INSTALLER_TMP" --version "$VERSION"

          # Clean up.
          echo "Cleaning up"
          rm -rf "$HELM_INSTALLER_TMP"
        fi

        # Add the Helm tool dir to the path.
        echo "Adding Helm to path"
        echo "$HELM_TOOL_DIR" >> "$GITHUB_PATH"

    - name: Print installed Helm version
      shell: bash
      run: |
        helm version
