name: 'helm'
description: 'A GitHub Action to run Helm commands'
author: 'Hidde Beydals'
branding:
  icon: 'command'
  color: 'blue'
inputs:
  version:
    description: 'strict semver'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
