name: Setup SOPS
description: A GitHub Action for running sops commands
author: Soule BA
branding:
  color: blue
  icon: command
inputs:
  version:
    description: "strict semver"
    required: true
    default: "3.7.1"
runs:
  using: composite
  steps:
    - name: "Download and copy the binary to /usr/local/bin"
      shell: bash
      run: |
        VERSION=${{ inputs.version }}
        REPO_URL=https://github.com/mozilla/sops/releases/download
        BIN_URL="${REPO_URL}/v${VERSION}/sops-v${VERSION}.linux"
        curl -fL --no-progress-meter ${BIN_URL} -o /tmp/sops
        chmod +x /tmp/sops
        sudo mv /tmp/sops /usr/local/bin
        which sops
        sops --version