name: actions

on:
  pull_request:
  push:
    paths:
      - 'actions/**'
    branches:
      - main

permissions: read-all

jobs:
  actions:
    strategy:
      fail-fast: false
      matrix:
        version: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.version }}
    name: actions on ${{ matrix.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup yq
        uses: ./actions/yq
      - name: Setup kubeconform
        uses: ./actions/kubeconform
      - name: Setup envtest
        uses: ./actions/envtest
      - name: Setup helm
        uses: ./actions/helm
      - name: Setup kubectl
        uses: ./actions/kubectl
      - name: Setup kustomize
        uses: ./actions/kustomize
      - name: Setup sops
        uses: ./actions/sops
