name: fuzz

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  smoketest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
    - name: Setup Go
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        go-version: 1.20.x
        # https://github.com/actions/setup-go/blob/main/docs/adrs/0000-caching-dependencies.md#example-of-real-use-cases
        cache-dependency-path: |
          **/go.sum
          **/go.mod
    - name: Smoke test Fuzzers
      run: make fuzz-smoketest
