name: e2e

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  git-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITPROVIDER_BOT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Since this is a monorepo, changes in other packages will also trigger these e2e tests
      # meant only for the git package. This detects us whether the changed files are part of the
      # git directory. Subsequent steps check if this is true, before executing, thus helping us
      # run these tests only when there are changes to the git package.
      - name: Check for changes to git/
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            git:
              - 'git/**'
      - name: Restore Go cache
        if: steps.filter.outputs.git == 'true'
        uses: actions/cache@v1
        with:
          path: /home/runner/work/_temp/_github_home/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        if: steps.filter.outputs.git == 'true'
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Run tests
        if: steps.filter.outputs.git == 'true'
        run: cd git/internal/e2e && ./run.sh
