name: integration-aws

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"
  # push:
  #   branches:
  #     - main

permissions:
  contents: read
  id-token: write # Required for obtaining AWS OIDC federated credential.

jobs:
  oci-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./oci/tests/integration
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: 1.23.x
          cache-dependency-path: oci/tests/integration/go.sum
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.OCI_E2E_AWS_ASSUME_ROLE_NAME }}
          role-session-name: OCI_GH_Actions
          aws-region: ${{ vars.AWS_REGION }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349  # v3.7.1
      - name: Set dynamic variables in .env
        run: |
          cat > .env <<EOF
          export TF_VAR_rand=${RANDOM}
          export TF_VAR_tags='{"environment"="github", "ci"="true", "repo"="pkg", "createdat"="$(date -u +x%Y-%m-%d_%Hh%Mm%Ss)"}'
          EOF
      - name: Print .env for dynamic tag value reference
        run: cat .env
      - name: Build test app
        run: make docker-build
      - name: Run tests
        run: . .env && make test-aws
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          TF_VAR_cross_region: ${{ vars.OCI_E2E_TF_VAR_cross_region }}
      - name: Ensure resource cleanup
        if: ${{ always() }}
        run: . .env && make destroy-aws
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          TF_VAR_cross_region: ${{ vars.OCI_E2E_TF_VAR_cross_region }}
